package com.global.model.bc.view;

import com.global.model.bc.entity.InvLineEOImpl;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 26 03:09:21 AST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvLineVORowImpl extends ViewRowImpl {
    public static final int ENTITY_INVLINEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        InvLineId,
        InvId,
        ProdId,
        QtyCount,
        Discount,
        UnitPrice,
        LineTotal,
        InvVO,
        ProdVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int INVLINEID = AttributesEnum.InvLineId.index();
    public static final int INVID = AttributesEnum.InvId.index();
    public static final int PRODID = AttributesEnum.ProdId.index();
    public static final int QTYCOUNT = AttributesEnum.QtyCount.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int LINETOTAL = AttributesEnum.LineTotal.index();
    public static final int INVVO = AttributesEnum.InvVO.index();
    public static final int PRODVO = AttributesEnum.ProdVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvLineVORowImpl() {
    }

    /**
     * Gets InvLineEO entity object.
     * @return the InvLineEO
     */
    public InvLineEOImpl getInvLineEO() {
        return (InvLineEOImpl) getEntity(ENTITY_INVLINEEO);
    }

    /**
     * Gets the attribute value for INV_LINE_ID using the alias name InvLineId.
     * @return the INV_LINE_ID
     */
    public BigDecimal getInvLineId() {
        return (BigDecimal) getAttributeInternal(INVLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INV_LINE_ID using the alias name InvLineId.
     * @param value value to set the INV_LINE_ID
     */
    public void setInvLineId(BigDecimal value) {
        setAttributeInternal(INVLINEID, value);
    }

    /**
     * Gets the attribute value for INV_ID using the alias name InvId.
     * @return the INV_ID
     */
    public BigDecimal getInvId() {
        return (BigDecimal) getAttributeInternal(INVID);
    }

    /**
     * Sets <code>value</code> as attribute value for INV_ID using the alias name InvId.
     * @param value value to set the INV_ID
     */
    public void setInvId(BigDecimal value) {
        setAttributeInternal(INVID, value);
    }

    /**
     * Gets the attribute value for PROD_ID using the alias name ProdId.
     * @return the PROD_ID
     */
    public BigDecimal getProdId() {
        return (BigDecimal) getAttributeInternal(PRODID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_ID using the alias name ProdId.
     * @param value value to set the PROD_ID
     */
    public void setProdId(BigDecimal value) {
        setAttributeInternal(PRODID, value);
    }

    /**
     * Gets the attribute value for QTY_COUNT using the alias name QtyCount.
     * @return the QTY_COUNT
     */
    public BigDecimal getQtyCount() {
        return (BigDecimal) getAttributeInternal(QTYCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY_COUNT using the alias name QtyCount.
     * @param value value to set the QTY_COUNT
     */
    public void setQtyCount(BigDecimal value) {
        setAttributeInternal(QTYCOUNT, value);
    }

    /**
     * Gets the attribute value for DISCOUNT using the alias name Discount.
     * @return the DISCOUNT
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCOUNT using the alias name Discount.
     * @param value value to set the DISCOUNT
     */
    public void setDiscount(BigDecimal value) {
        setAttributeInternal(DISCOUNT, value);
//        calculateLineTotal();
    }


    /**
     * Gets the attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @return the UNIT_PRICE
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @param value value to set the UNIT_PRICE
     */
    public void setUnitPrice(BigDecimal value) {
        setAttributeInternal(UNITPRICE, value);
//        calculateLineTotal();
    }

    /**
     * Gets the attribute value for LINE_TOTAL using the alias name LineTotal.
     * @return the LINE_TOTAL
     */
    public BigDecimal getLineTotal() {
        return (BigDecimal) getAttributeInternal(LINETOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_TOTAL using the alias name LineTotal.
     * @param value value to set the LINE_TOTAL
     */
    public void setLineTotal(BigDecimal value) {
        setAttributeInternal(LINETOTAL, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvVO.
     */
    public RowSet getInvVO() {
        return (RowSet) getAttributeInternal(INVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProdVO.
     */
    public RowSet getProdVO() {
        return (RowSet) getAttributeInternal(PRODVO);
    }
}

